name: Steps workflow
on:
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - id: random
        run: exit $(($RANDOM % 2 == 0))
      - if: always()
        run: echo ${{ steps.random.outcome }}