name: Checkout Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
        with:
          repository: actions/checkout
          ref: v3.6.0
      - run: ls -al
