name: Checkout Workflow
on: 
  workflow_dispatch
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3.6.0
        with:
          repository: actions/checkout
          ref: v3.6.0
      - run: ls -al
