name: Workflows Names - github-action-workflow_call-01
run-name: Runs Names - github-action-workflow_call-01 🚀
on: 
  workflow_dispatch

jobs:
  Jobs-Names-github-action-workflow_call-01:
    uses: ./.github/workflows/github-action-workflow_call.yml
    with:
      environment: production
