name: Greeting on variable day

on:
  workflow_dispatch : 수동으로 실행, manully

env:
  DAY_OF_WEEK: Thursday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello GithubActions it's Thursday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: GithubActions
