name: varTest
run-name: run varTest

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Thursday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello VAR_TEST"
        run: echo "Hello ${{ vars.VARS_TEST }}"
      
